### ISSUE TITLE
vmbr check

### ISSUE THREAD

**Issue by simonccc** [simonccc/kopsrox#13]
`vmbr01 bridge not found - available:
Traceback (most recent call last):
  File "/home/simonc/GIT/kopsrox/./kopsrox.py", line 15, in <module>
    import kopsrox_config as kopsrox_config
  File "/home/simonc/GIT/kopsrox/lib/kopsrox_config.py", line 133, in <module>
    if i.get("type") == 'bridge':
       ^^^^^
AttributeError: 'str' object has no attribute 'get'`

**Comment by simonccc** [comment]
fixed
