### ISSUE TITLE
error checking when vms have no internet connection

### ISSUE THREAD

**Issue by simonccc** [simonccc/kopsrox#15]
errors are not helpful when running eg `etcd list`

**Comment by simonccc** [comment]
```simonc@nuc ~/GIT/kopsrox $ ./kopsrox.py etcd list
Traceback (most recent call last):
  File "/home/simonc/GIT/kopsrox/./kopsrox.py", line 90, in <module>
    exec_verb = __import__('verb_' + verb)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonc/GIT/kopsrox/lib/verb_etcd.py", line 87, in <module>
    s3_run('ls')
  File "/home/simonc/GIT/kopsrox/lib/verb_etcd.py", line 70, in s3_run
    cmd_out = proxmox.qaexec(masterid, k3s_run).rstrip()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonc/GIT/kopsrox/lib/kopsrox_proxmox.py", line 84, in qaexec
    return(pid_check['err-data'])
           ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'err-data'```
